title: Translational Livestock Microbiome Research Lab
email: zisan.rr@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Decoding host-microbe interactions to improve animal health, production efficiency, and sustainability.

# =============================================================
# THE CRITICAL SETTINGS - DO NOT CHANGE THESE
# =============================================================
url: "https://tlmicrobiomelab.github.io" 
baseurl: "" 
# =============================================================

theme: minima
plugins:
  - jekyll-feed
